### ISSUE TITLE
Deploy to Asure

### ISSUE THREAD

**Issue by r9young** [r9young/copilot-nodejs-todo-template#1]
You are asking for a detailed breakdown of specific steps to set up Azure credentials and create a CI/CD workflow for deploying a Node.js app to Azure using GitHub Actions. Here's a step-by-step guide:

---

### **Step 1: Set Up Azure Credentials**
1. Open a terminal at the root of your project.
2. Run the setup script:
   ```bash
   ./setup.sh
   ```
   - **Purpose**: Automates Azure and GitHub login, creates a service principal, and adds the `AZURE_CREDENTIALS` secret to your GitHub repository.
3. Follow the prompts:
   - Login to your Azure account.
   - Select the Azure subscription to use.
   - Login to your GitHub account.

---

### **Step 2: Add a CI/CD Workflow**
1. Create a new file in your project:
   ```
   .github/workflows/deploy.yml
   ```

2. Add the following basic workflow template:
   ```yaml
   name: Deploy to Azure

   on:
     push:
       branches:
         - main

   jobs:
     build:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v4
         - name: Use Node.js 20
           uses: actions/setup-node@v4
           with:
             node-version: 20
         - name: Install dependencies
           run: npm ci
         - name: Run tests
           run: npm test
         - name: Build
           run: npm run build
         - name: Login to Azure
           uses: azure/login@v2
           with:
             creds: ${{ secrets.AZURE_CREDENTIALS }}
   ```

---

#### Add Azure CLI commands for deployment:

1. **Create a Resource Group**:
   Add this comment and command:
   ```yaml
         # Create resource group
         - name: Create resource group
           run: az group create --name rg-copilot-nodejs-todo --location eastus
   ```

2. **Create Cosmos DB Account**:
   ```yaml
         # Create Cosmos DB account
         - name: Create Cosmos DB account
           run: az cosmosdb create --name copilot-nodejs-todo --resource-group rg-copilot-nodejs-todo
   ```

3. **Create Database**:
   ```yaml
         # Create database
         - name: Create database
           run: az cosmosdb sql database create --account-name copilot-nodejs-todo --resource-group rg-copilot-nodejs-todo --name todos
   ```

4. **Create a Container**:
   ```yaml
         # Create container
         - name: Create container
           run: az cosmosdb sql container create --account-name copilot-nodejs-todo --resource-group rg-copilot-nodejs-todo --database-name todos --name tasks --partition-key-path /id --throughput 400
   ```

5. **Deploy the Web App**:
   ```yaml
         # Deploy web app
         - name: Deploy web app
           run: az webapp up --sku F1 --name nodejs-todo-YOUR_USERNAME --resource-group rg-copilot-nodejs-todo --runtime "node|20-lts"
   ```

---

### **Step 4: Configure Environment Variables**
1. Retrieve the Cosmos DB endpoint:
   ```yaml
         # Retrieve Cosmos DB endpoint
         - name: Retrieve Cosmos DB endpoint
           run: |
             cosmos_endpoint=$(az cosmosdb show --name copilot-nodejs-todo --resource-group rg-copilot-nodejs-todo --query documentEndpoint --output tsv)
   ```

2. Retrieve the Cosmos DB key:
   ```yaml
         # Retrieve Cosmos DB key
         - name: Retrieve Cosmos DB key
           run: |
             cosmos_key=$(az cosmosdb keys list --name copilot-nodejs-todo --resource-group rg-copilot-nodejs-todo --query primaryMasterKey --output tsv)
   ```

3. Set these variables in the web app:
   ```yaml
         # Set Cosmos variables in web app
         - name: Set Cosmos variables in web app
           run: |
             az webapp config appsettings set --name nodejs-todo-YOUR_USERNAME --resource-group rg-copilot-nodejs-todo --settings COSMOS_ENDPOINT=$cosmos_endpoint COSMOS_KEY=$cosmos_key --output none
   ```

---

### **Step 5: Finalize and Push**
1. Save the `deploy.yml` file.
2. Commit and push your changes to the `main` branch:
   ```bash
   git add .github/workflows/deploy.yml
   git commit -m "Add GitHub Actions CI/CD workflow"
   git push origin main
   ```

---

### **Outcome**
- The workflow will trigger on every push to the `main` branch.
- It will test, build, and deploy your Node.js app to Azure, including setting up Cosmos DB and environment variables.
